### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Eximinati** [Reubencfernandes/anime-character-random#2]
Can you make it to fetch only female characters?  @Reubencfernandes

**Comment by Reubencfernandes** [comment]
i dont think thats possible

**Comment by Eximinati** [comment]
> i dont think thats possible

You can🐦

By make json file or by my waifu list or something

**Comment by Reubencfernandes** [comment]
make json file of what ? 
to get female characters you will have to use AI to detect whether the character is male or female

**Comment by Eximinati** [comment]
> make json file of what ? to get female characters you will have to use AI to detect whether the character is male or female

You can just write id of female characters and use js module to fetch it. Some female waifu id list (https://github.com/Eximinati/WAifu) node module (https://www.npmjs.com/package/@shineiichijo/marika)
